//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onllineexam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionData
    {
        public int testid { get; set; }
        public long Question_number { get; set; }
        public string Question { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public Nullable<int> correct_option { get; set; }
        public string Level { get; set; }
        public string Description { get; set; }
    
        public int selectedvalue { get; set; }
        public virtual TestGenerator TestGenerator { get; set; }
    }
}
