//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onllineexam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionFile
    {
        public int testid { get; set; }
        public string subname { get; set; }
        public string Question_file { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual TestGenerator TestGenerator { get; set; }
    }
}
