//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onllineexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Results = new HashSet<Result>();
            this.TestAccessors = new HashSet<TestAccessor>();
        }
    
        public int Stu_ID { get; set; }
        [Display(Name ="First Name")]
        [Required]
        public string F_Name { get; set; }
        [Display(Name = "Last Name")]
        [Required]
        public string L_Name { get; set; }
        [Display(Name = "Email ID")]
        
        public string Stu_Email { get; set; }
        [Display(Name = "Phone")]
        [Required]
        public string Phone { get; set; }
        [Display(Name = "City")]
        [Required]
        public string City { get; set; }
        [Display(Name = "Date of Birth")]
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }
        [Display(Name = "State")]
        [Required]
        public string State { get; set; }
        [Display(Name = "Qualification")]
        [Required]
        public string Qualification { get; set; }
        [Display(Name = "Year Of Completion")]
        [Required]
        [DataType(DataType.Date)]
        public string Year_of_comp { get; set; }
    
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestAccessor> TestAccessors { get; set; }
    }
}
