//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onllineexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.TestGenerators = new HashSet<TestGenerator>();
        }

        public int TeacherID { get; set; }
        [Required]
        [Display(Name ="Teacher Name")]
        public string Teach_Name { get; set; }
        [Required]
        [MinLength(10)]
        [MaxLength(10)]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        public string Teach_contact { get; set; }
        public string Teach_Email { get; set; }
    
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestGenerator> TestGenerators { get; set; }
    }
}
